### ISSUE TITLE
Add GPIO output

### ISSUE THREAD

**Issue by laurensoosting** [balenalabs/balena-sound#100]
Add GPIO output which can be used to enable an amplifier when music is playing.

**Comment by tmigone** [comment]
Hi @laurensoosting this feature is already supported via `bluetooth scripts`:
- https://github.com/balenalabs/balena-sound#bluetooth-scripts-optional

Is this useful to you?

**Comment by laurensoosting** [comment]
Im mainly looking for this feature to use with spotify. I hink this could be a nice adition. On this moment the amplifier is always on.

**Comment by tmigone** [comment]
I see, in that case, yes, that is currently not possible. But it's a nice addition so we'll add it to the backlog. Thanks for the suggestion!

**Comment by AlexProgrammerDE** [comment]
@tmigone and @laurensoosting i found this wiki page of librespot: https://github.com/librespot-org/librespot/wiki/Options . It has an option named onevent. I will do some research now.

**Comment by tmigone** [comment]
This will be possible when 3.x is released with play/stop event hooks.

**Comment by AlexProgrammerDE** [comment]
This seems fixed then?

**Comment by shawaj** [comment]
@AlexProgrammerDE reckon it is worth adding some documentation about how to do this? I am not entirely sure of how to use the hooks. Haven't played around with it.

**Comment by AlexProgrammerDE** [comment]
@shawaj yeah docs on this would be good. @tmigone can you give us a look into how this works now?

**Comment by tmigone** [comment]
Added to the TODO in #393
