### ISSUE TITLE
Add HIFI Berry AMP2 to Configuration

### ISSUE THREAD

**Issue by cur1ou5soul** [balenalabs/balena-sound#109]
How can I add HiFi Berry AMP2 as output device?

**Comment by tmigone** [comment]
Hi @cur1ou5soul were you able to get the DAC to work?

Adding support for that DAC should be pretty straightforward. Please follow [this](https://github.com/balenalabs/balena-sound/blob/master/DAC_configuration.md) guide and use `hifiberry-dacplus` for the `BALENA_HOST_CONFIG_dtoverlay` variable. 

If you can test this and confirm it works we can add it to the docs as a supported DAC.
