### ISSUE TITLE
Can't restart services after shutdown of Pi4

### ISSUE THREAD

**Issue by Ralphie71** [balenalabs/balena-sound#110]
Hello guys,

I'm new to balena-sound and I got into troubles after the shutdown of my Pi4 where I had installed the balena-sound system.
Just after the installation everything worked fine so I used the shutdown commend from dashboard  menu and I powerd off the PI4.  Next day when I switched it on again I saw it working on dashboard ( on line ) but none of services was running. All were in Exited status.
I tried the Restart commend from the dashboard menu but I got a red allert on the top of dashboard saying:  Request error: tunneling socket could not be established, cause=socket hang up.

Could you please help me how to restore the services or get them running again ?  Thanks in advance for your help.

**Comment by tmigone** [comment]
Hello @Ralphie71, thanks for reaching out. This looks like a networking problem, but without additional info it's hard to know. 
As I don't think this is `balena-sound` specific, Can you please take this issue to our [forums](https://forums.balena.io/)? We have support agents pretty much all day that will be glad to assist you with this. 
Cheers!
