### ISSUE TITLE
Is it possible to use RaspiAudio DAC ?

### ISSUE THREAD

**Issue by boscar98** [balenalabs/balena-sound#120]
Is it possible to use RaspiAudio DAC (https://www.raspiaudio.com/home) ? I tried with the Pimoroni pHAT DAC config because it looked similar to me but it didn't work.

**Comment by chrisys** [comment]
Looking at the config it looks like it should work with `dtoverlay=hifiberry-dac` - is that the one you tried?

**Comment by boscar98** [comment]
Yeah i tried with this one :/

**Comment by chrisys** [comment]
Ah ok, what I'd recommend doing next, is to take a look at what the install script for this device does and make sure all those steps are carried out on your device. At first glance, many of them will be taken care of, but particularly look into the asound.conf changes that are being made.

**Comment by AlexProgrammerDE** [comment]
@chrisys i just looked into the installer. If you download the installer here: script.raspiaudio.com
and have a look at line 333-338:

    if [ -e $CONFIG ] && grep -q "^dtoverlay=hifiberry-dac$" $CONFIG; then
      echo "dtoverlay already active"
    else
       echo "dtoverlay=hifiberry-dac" | sudo tee -a $CONFIG
       ASK_TO_REBOOT=true
    fi

The dtoverly should be `hifiberry-dac`.

**Comment by boscar98** [comment]
Well, it's maybe the raspberry itself, he's not very new. i'll try with an other one. Thanks for your help !
