### ISSUE TITLE
multi-room: Add option to force master server IP via env var

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#122]
Pi0 devices can miss event broadcasts that announce a new master. Based on my testing this is rare and only on pi0 devices due to them barely being able to run balena-sound stack. 

An option to remedy this could be adding an env var `FORCE_MASTER_SERVER` that:
- forces all devices on the fleet to point to that server
- disables autoconfig on stream start

**Comment by AlexProgrammerDE** [comment]
@tmigone this is not practical for consumers. They don´t have access to the cloud dashboard.

**Comment by tmigone** [comment]
This is now possible as of balenaSound v3.0 by setting the `SOUND_MULTIROOM_MASTER` env var: https://sound.balenalabs.io/docs/customization#multi-room
