### ISSUE TITLE
balena push error after bıid cant upload it

### ISSUE THREAD

**Issue by dikeckaan** [balenalabs/balena-sound#124]
as you shown my cmd output is here. i can connect ssh and already enabled local mode

`C:\Users\BERKAY\Desktop\balena-sound-master>balena ssh 192.168.0.19
[debug] original argv0="C:\Program Files\balena-cli\bin\\..\client\bin\node.exe" argv=[C:\Program Files\balena-cli\client\bin\node.exe,C:\Program Files\balena-cli\client\bin\run,ssh,192.168.0.19] length=4
Last login: Wed Mar 25 11:55:01 2020 from 52.4.252.97
root@82d75e7:~# exit
logout
Connection to 192.168.0.19 closed.

C:\Users\BERKAY\Desktop\balena-sound-master>balena push 192.168.0.19
[debug] original argv0="C:\Program Files\balena-cli\bin\\..\client\bin\node.exe" argv=[C:\Program Files\balena-cli\client\bin\node.exe,C:\Program Files\balena-cli\client\bin\run,push,192.168.0.19] length=4
[debug] Using . as build source
[Debug]   Checking we can access device
[Debug]   Sending request to http://192.168.0.19:48484/ping
[Debug]   Checking device version: 10.6.27
[Info]    Starting build on device 192.168.0.19
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "."
[Debug]   Creating project...
[Debug]   Tarring all non-ignored files...
[Debug]   Sending request to http://192.168.0.19:48484/v2/local/device-info
[Debug]   Found build tasks:
[Debug]       bluetooth-audio: build [./bluetooth-audio]
[Debug]       airplay: build [./airplay]
[Debug]       spotify: build [./spotify]
[Debug]       fleet-supervisor: build [./fleet-supervisor]
[Debug]       snapcast-server: build [./snapcast-server]
[Debug]       snapcast-client: build [./snapcast-client]
[Debug]   Resolving services with [raspberrypi3-64|aarch64]
[Debug]   Found project types:
[Debug]       bluetooth-audio: Architecture-specific Dockerfile
[Debug]       airplay: Dockerfile.template
[Debug]       spotify: Architecture-specific Dockerfile
[Debug]       fleet-supervisor: Dockerfile.template
[Debug]       snapcast-server: Architecture-specific Dockerfile
[Debug]       snapcast-client: Architecture-specific Dockerfile
[Debug]   Probing remote daemon for cache images
[Debug]   Using 2 on-device images for cache...
[Debug]   Starting builds...
[Build]   [spotify] Step 1/6 : FROM balenalib/raspberrypi3-debian:buster
[Build]   [fleet-supervisor] Step 1/9 : FROM balenalib/raspberrypi3-64-alpine-node
[Build]   [snapcast-server] Step 1/12 : FROM balenalib/raspberrypi3-debian:buster
[Build]   [bluetooth-audio] Step 1/17 : FROM balenalib/raspberrypi3-debian:stretch
[Build]   [snapcast-client] Step 1/11 : FROM balenalib/raspberrypi3-debian:buster
[Build]   [airplay] Step 1/7 : FROM balenalib/raspberrypi3-64-debian:buster
[Debug]   Setting device state...
[Debug]   Sending request to http://192.168.0.19:48484/v2/local/target-state
[Debug]   Sending target state: {"local":{"name":"wirelesspotiy","config":{"SUPERVISOR_DELTA_VERSION":"3","HOST_CONFIG_disable_overscan":"1","HOST_CONFIG_disable_splash":"1","HOST_CONFIG_dtoverlay":"\"vc4-kms-v3d\"","HOST_CONFIG_dtparam":"\"audio=on\",\"i2c_arm=on\",\"spi=on\",\"audio=on\"","HOST_CONFIG_enable_uart":"1","HOST_CONFIG_gpu_mem":"16","SUPERVISOR_LOCAL_MODE":"1","SUPERVISOR_POLL_INTERVAL":"900000","SUPERVISOR_VPN_CONTROL":"true","SUPERVISOR_INSTANT_UPDATE_TRIGGER":"true","SUPERVISOR_CONNECTIVITY_CHECK":"true","SUPERVISOR_LOG_CONTROL":"true","SUPERVISOR_DELTA":"false","SUPERVISOR_DELTA_REQUEST_TIMEOUT":"30000","SUPERVISOR_DELTA_APPLY_TIMEOUT":"0","SUPERVISOR_DELTA_RETRY_COUNT":"30","SUPERVISOR_DELTA_RETRY_INTERVAL":"10000","SUPERVISOR_OVERRIDE_LOCK":"false","SUPERVISOR_PERSISTENT_LOGGING":"false"},"apps":{"1":{"name":"localapp","commit":"localrelease","releaseId":"1","services":{"1":{"environment":{},"labels":{"io.balena.features.dbus":"1"},"restart":"always","network_mode":"host","privileged":true,"volumes":["bluetoothcache:/var/cache/bluetooth","snapcast:/var/cache/snapcast"],"imageId":1,"serviceName":"bluetooth-audio","serviceId":1,"image":"local_image_bluetooth-audio:latest","running":true},"2":{"environment":{},"labels":{"io.balena.features.dbus":"1"},"restart":"always","network_mode":"host","privileged":true,"volumes":["snapcast:/var/cache/snapcast"],"imageId":2,"serviceName":"airplay","serviceId":2,"image":"local_image_airplay:latest","running":true},"3":{"environment":{},"labels":{},"restart":"always","network_mode":"host","privileged":true,"volumes":["spotifycache:/var/cache/raspotify","snapcast:/var/cache/snapcast"],"imageId":3,"serviceName":"spotify","serviceId":3,"image":"local_image_spotify:latest","running":true},"4":{"environment":{},"labels":{"io.balena.features.supervisor-api":"1"},"restart":"on-failure","network_mode":"host","privileged":true,"ports":["3000:3000"],"imageId":4,"serviceName":"fleet-supervisor","serviceId":4,"image":"local_image_fleet-supervisor:latest","running":true},"5":{"environment":{},"labels":{},"restart":"on-failure","ports":["1704:1704","1705:1705"],"volumes":["snapcast:/var/cache/snapcast"],"imageId":5,"serviceName":"snapcast-server","serviceId":5,"image":"local_image_snapcast-server:latest","running":true},"6":{"environment":{},"labels":{},"restart":"on-failure","network_mode":"host","privileged":true,"volumes":["snapcast:/var/cache/snapcast"],"imageId":6,"serviceName":"snapcast-client","serviceId":6,"image":"local_image_snapcast-client:latest","running":true}},"volumes":{"spotifycache":{},"bluetoothcache":{},"snapcast":{}},"networks":{}}}},"dependent":{"config":{}}}
[Debug]   Sending request to http://192.168.0.19:48484/v2/local/target-state
ECONNRESET: read ECONNRESET
Error: read ECONNRESET
    at TCP.onread (net.js:622:25)
From previous event:
    at Function.promisifiedRequest (C:\Program Files\balena-cli\client\build\utils\device\api.js:128:25)
    at DeviceAPI.setTargetState (C:\Program Files\balena-cli\client\build\utils\device\api.js:25:26)
    at Object.deployToDevice (C:\Program Files\balena-cli\client\build\utils\device\deploy.js:114:15)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/`

**Comment by tmigone** [comment]
Hello @dikeckaan, thanks for reporting this. Without more information is hard to diagnose this problem, but this looks like a problem either with balena CLI or our builders. Can you post this issue at our [forums](https://forums.balena.io)? We have support agents pretty much all day that can provide you better assistance than in this repo. Thank you!
