### ISSUE TITLE
DNLA/Upnp

### ISSUE THREAD

**Issue by peteretep** [balenalabs/balena-sound#139]
The `airplay` service can be used to stream from an apple device. You can't do similar from an android or other device.
The bluetooth service has limitations.
The equivalent service for android/other devices is DNLA/UPnP.
Would it be possible to add a UPnP service, and if so has anyone explored this?
I haven't been able to get my head around the various UPnP clients etc and would like some pointers.

**Comment by AlexProgrammerDE** [comment]
@peteretep i have opened a work in progress PR. it will take some time, but connecting already works. I will later add the multiroom feature.

**Comment by peteretep** [comment]
Great! I'll try it out. Thanks.
