### ISSUE TITLE
Bad noise RPi

### ISSUE THREAD

**Issue by polmdm** [balenalabs/balena-sound#142]
Hi,
I’ve just flashed balenaOS + balena sound following the instructions on website. I’m currently using a RPi 3 with 32-bit software and when i connect my amplifier the only thing I ear is a bad noise and even trying to play some music (both Spotify or Bluetooth) the noise won’t stop.

To check that amplifier and cable work properly I’ve tried to connect my phone and everything works properly. It’s my fault or there’s something i can do?

**Comment by AlexProgrammerDE** [comment]
@polmdm i have the same issue. What PSU are you using?

**Comment by polmdm** [comment]
@AlexProgrammerDE what do you mean with PSU?

So far what I've discovered:
 - with the earpods the issue not occur at all, some lag but no background noise
 - with a different cable the noise is way less

but in both cases very low volume!

**Comment by AlexProgrammerDE** [comment]
@polmdm PSU=Power Supply Unit
Not certified PSU´s can cause issues. So what are you using?

**Comment by polmdm** [comment]
You mean for the Raspberry?

**Comment by AlexProgrammerDE** [comment]
@polmdm yes. Which power supply gives your Pi the energy?

**Comment by polmdm** [comment]
I'm using a power supply bought in a starter kit for rpi, it supply 5V and 2.5 A, the model is XS-0502500SEUD should I change it?

**Comment by AlexProgrammerDE** [comment]
@polmdm i think there are differences between some PSUs. Here a example https://github.com/balenalabs/balena-sound/issues/62#issuecomment-605265537 

Can you try it with other PSU´s

**Comment by polmdm** [comment]
@AlexProgrammerDE since I don't have other PSU and since I would like to develop this project on a Raspberry with Docker I think I'll go for another solution. Thanks you very much!

**Comment by tmigone** [comment]
Closing, feel free to reopen.
