### ISSUE TITLE
Custom Bluetooth name not working

### ISSUE THREAD

**Issue by AedanBarr** [balenalabs/balena-sound#146]
**Describe the bug**
I have a custom name set but now it just says “balenaSound Spotify cf65”. This has only happed when you updated to 2.1.1

**Expected behavior**
I expect it to show “AEDAN’S RASPBERRY PI”

**Screenshots**
![A58ED790-2DDD-4274-A29C-7140B29F9C4F](https://user-images.githubusercontent.com/59069724/78474279-dc284f00-7711-11ea-99f8-145af21f4699.png)
![215F2BC3-4BB9-421B-AAEB-8968A24627D8](https://user-images.githubusercontent.com/59069724/78474292-dd597c00-7711-11ea-808a-3e60691fa287.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR 
 - OS: IOS 13.4

**Comment by AlexProgrammerDE** [comment]
@AedanBarr we updated the variable. BalenaSound supports now Airplay, Bluetooth, Spotify Connect and soon UPnP. `BLUETOOTH_DEVICE_NAME` is no longer right. We updated it to: `DEVICE_NAME`.

**Comment by AedanBarr** [comment]
Thanks. That explains why it was not working
