### ISSUE TITLE
WIFI-Support?

### ISSUE THREAD

**Issue by diwaffm** [balenalabs/balena-sound#160]
Since I didn't read anything about this, I wonder, if BalenaSound supports the Raspi 4s WIFI module?

I like to build a multi-room enviorment - but I don't hat LAN in all the rooms (e.g. the kitchen oder the bathroom)

Ciao

dirk

**Comment by AlexProgrammerDE** [comment]
@diwaffm yes balenaOS supports most WLAN modules. Including all of the Raspberry Pi series. Before downloading the image can you enter the SSID of your WLAN and the password. The Pi will then automaticly connect to the specified WIFI on boot.

**Comment by AlexProgrammerDE** [comment]
@diwaffm i will close this issue now. Feel free to reopen if you have more questions about this.
