### ISSUE TITLE
BalenaSound (balenaOS 2.48.0+rev1) not working after installing JustBoom Digi HAT on Raspberry Pi 4 #473

### ISSUE THREAD

**Issue by jonrrivera** [balenalabs/balena-sound#163]
Hi,

I have been enjoying my BalendaSound with my new Raspberry Pi 4. But when I installed the JustBoom Digi HAT and edited the configuration it suddenly stopped working. The console is outputting some errors, but I really don’t know how to debug them…

Any help would be appreciated thanks!

<img width="1240" alt="Screen Shot 2020-04-14 at 1 03 28 PM" src="https://user-images.githubusercontent.com/18686388/79254142-45b30680-7e52-11ea-8731-eb7643e78d00.png">

<img width="1222" alt="Screen Shot 2020-04-14 at 1 03 06 PM" src="https://user-images.githubusercontent.com/18686388/79254145-464b9d00-7e52-11ea-9a98-32530a1f508a.png">

HOST OS VERSION
balenaOS 2.48.0+rev1

SUPERVISOR VERSION
10.8.0

CURRENT RELEASE
f49e2692bbf334167693b8d607d7a504

**Comment by AlexProgrammerDE** [comment]
@jonrrivera you used the wrong dtoverlay. Please change `justboom-dac` to `justboom-digi` and report me the result.

**Comment by jonrrivera** [comment]
that was it! thank you so much!
