### ISSUE TITLE
How to disable Spotify?

### ISSUE THREAD

**Issue by wangjunwei87** [balenalabs/balena-sound#168]
Buletooth and Airplay are enough for me? How to disable spotify?

**Comment by Baryczka** [comment]
You can disable services in balena device dashboard or either comment proper parts in docker-compose.yml. Maybe there are more elegant way to do it but these 2 are straight forward

**Comment by AlexProgrammerDE** [comment]
@wangjunwei87 Baryczka is right. We recommend deleting the spotify entry in the docker-compose.yml file. Closing.

**Comment by wangjunwei87** [comment]
@Baryczka @AlexProgrammerDE Yes,  it will work, but everytime balena-sound updates, I will have to do it again. Is it possible to add some env variable like `DISALBE_MULTI_ROOM` (eg: `DISABLE_SPOTIFY` ) to disable spotify?
