### ISSUE TITLE
USB Audio and DAC X400

### ISSUE THREAD

**Issue by isteaks** [balenalabs/balena-sound#180]
I have a USB audio class device connected to my Raspberry pi that is mapped on HW:0 and My DAC is mapped on HW:1. I want to play music using my DAC on HW:1. I was able to do it on the bluetooth service playing with a .asoundrc but how can I change the default audio playback device on Airplay and the other sercices?

Thanks.

**Comment by AlexProgrammerDE** [comment]
@isteaks you are not using multiroom?

**Comment by tmigone** [comment]
Hey @isteaks, with the release of balenaSound v3.0 USB soundcards should be supported out of the box. Let us know if you have trouble setting it up or have any other questions. Thanks!
