### ISSUE TITLE
Allow toggling multi room flag more seamlessly

### ISSUE THREAD

**Issue by sradevski** [balenalabs/balena-sound#181]
Feedback/request from a user:

> At times I want to play music in multiple rooms at the same time, but at times my girlfriend would like to listen to certain music in let’s say the living room as I am listening to different music in let’s say the bedroom.
 Is there a more elegant way to achieve this than going into the settings and adding or removing the DISABLE_MULTI_ROOM command every time I would like to switch between local and multiroom playback?

This will require having some simple UI I guess

**Comment by AlexProgrammerDE** [comment]
This could be accomplished, by setting the master ip to `localhost`. Just needs some way to force the server.

**Comment by klausagnoletti** [comment]
Why not do it more Sonos-style by adding ‘zones’, with in practice is device groups which each can be played to individually. To use this, each zone would be its own BT device or Airplay/Spotify Connect device. Dunno if this is possible but surely would be nice.

**Comment by AlexProgrammerDE** [comment]
@klausagnoletti i think zones will be implemented by this PR: #153

**Comment by tmigone** [comment]
Changing device mode (MULTI_ROOM; STANDALONE) is now possible via the "secret" UI at `http://<DEVICE_IP>:3000/secret`. For now this is experimental, meaning that we don't advertise it too much as it still needs polishing and moar features will be added.

Groups/zones will be addressed in the future, for that follow #188.

I'll close this issue for now.
