### ISSUE TITLE
Google home support for playback and groups

### ISSUE THREAD

**Issue by finnje** [balenalabs/balena-sound#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It would be great if balena-sound devices were supported devices by google home. This would allow you to add them to rooms and control music playback by voice. For example "hey google play Pink Floyd on balena-sound"

**Comment by AlexProgrammerDE** [comment]
@finnje please take a look at #102 . I think that is what you are searching for. And please fill in the form and don't use the title as the whole explenation next time you submit a issue on github.
