### ISSUE TITLE
Volume Control for invidividual zones

### ISSUE THREAD

**Issue by martino-dot** [balenalabs/balena-sound#197]
**Is your feature request related to a problem? Please describe.**
I would like when I'm playing to all my zones that I can have a volume control for each zone.

**Describe the solution you'd like**
Simple volume slider for each device.

**Describe alternatives you've considered**
I know that you can connect to an individual device and control the volume through your phone or connecting to all the devices, and doing the same, but that controls the volume for everything!

**Additional context**
Since I have devices and amps in spaces that are not easily accessible, it would makes sense for me to be able to control the volume through the dashboard.

**Comment by ChestersGarage** [comment]
The snapcast client can do this.  It shows every server and client with volume sliders for each.  Immediate response and smooth.

**Comment by martino-dot** [comment]
Oh didn't know this. Thanks!
