### ISSUE TITLE
USB Sound Card

### ISSUE THREAD

**Issue by BGMine13** [balenalabs/balena-sound#198]
Hi !

My Raspberry Pi 3 B+ internal jack doesn't work, so I used a USB Sound Card before, and it worked (I was not using balenaSound). Now that I have balenaSound installed and running, functioning etc, I need my sound to go out whit my USB Sound Card.

BGMine 13

**Comment by martino-dot** [comment]
I think issue #9 has an answer to your question.

**Comment by tmigone** [comment]
Hey @BGMine13, unfortunately USB sound cards are not supported yet in balenaSound.

Some users have contributed work regarding it though, you can check it and might get it working. Check out this links:
- https://sound.balenalabs.io/docs/troubleshooting/#no-audio
- https://github.com/balenalabs/balena-sound/pull/192
