### ISSUE TITLE
Push audio through usb.

### ISSUE THREAD

**Issue by thecatman11** [balenalabs/balena-sound#203]
I am a noob at this and have a rpi zero w and it's running balena sound but I what to make the audio be be forced out of micro usb, is there a way to do this with a variable?

**Comment by mcohen75** [comment]
I was able to get this to work by disabling onboard audio.

Under Device Configuration for the device in question, edit DT parameters and set audio to off instead of on. I think you could probably also just remove the audio param.

**Comment by tmigone** [comment]
hi @mcohen75 are you talking about USB or HDMI?

**Comment by janek** [comment]
@mcohen75's suggestion worked for me to get sound working via USB (an external sound card connected via USB) on a Zero W. Thank you!

**Comment by tmigone** [comment]
USB sound cards are now supported with no configuration needed as of version 3.0.
