### ISSUE TITLE
Disable Bluetooth ding

### ISSUE THREAD

**Issue by Kore-Development** [balenalabs/balena-sound#210]
**Is your feature request related to a problem? Please describe.**
A way to disable the Bluetooth ding when connecting and disconnecting.

**Describe the solution you'd like**
Maybe an environment variable like how you would change the device name.

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexProgrammerDE** [comment]
Just set `CONNECTION_NOTIFY_VOLUME` to 0.

**Comment by tmigone** [comment]
Closing as the solution is what Alex proposed.
