### ISSUE TITLE
Deploy button doesnt work

### ISSUE THREAD

**Issue by AlexProgrammerDE** [balenalabs/balena-sound#216]
**Describe the problem**
When i click on the button i only get to the fleet page and nothing happens.

**Expected behavior**
Seeing a deploy interafce.

**Additional context**
How can i prefill the repo URL with help of the URL?

**Comment by tmigone** [comment]
hey @AlexProgrammerDE can you try this again? I just tried both from GitHub and landr page and it seems to work. Maybe there was a problem when you tried but now it's solved?

**Comment by AlexProgrammerDE** [comment]
@tmigone yes i just tested it again. Works great.
