### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by jackstirzaker** [balenalabs/balena-sound#222]
I am building from balena CLI on my Windows laptop and trying to put it on a Raspberry Pi 3. During the build, the CLI says:
`[Error]             An error occured: (HTTP code 404) no such image - no such image: 94d74402d54b: No such image: 94d74402d54b:latest `

**Comment by AlexProgrammerDE** [comment]
I had the same issue some time ago. You might have resolved it by trying it again. @tmigone do you have a idea why this occurs sometimes? Is this a issue with balena builders or is it a client side thing?

**Comment by jackstirzaker** [comment]
I am currently trying to build it again.

**Comment by jackstirzaker** [comment]
The build has succeeded.

**Comment by tmigone** [comment]
Hey @jackstirzaker @AlexProgrammerDE, this is indeed a temporary issue with our builders. Retrying the build will solve the problem as you suggested.
