### ISSUE TITLE
Add support for forked-daapd for multiroom support to existing airplay devices

### ISSUE THREAD

**Issue by soinkleined** [balenalabs/balena-sound#223]
**Is your feature request related to a problem? Please describe.**
Do not want to use snapcast for multiroom as I have many airplay speakers already.

**Describe the solution you'd like**
Use forked-daapd to stream to existing airplay receivers including support for a web interface to toggle airplay speakers and adjust individual and global volume.

**Describe alternatives you've considered**
node-airplayhub is cpu intensive and no longer supported

**Additional context**
n/a

**Comment by tmigone** [comment]
Hi, at this point we don't wan't to include a fully fledged audio server in balenaSound. This might change in the future, but for now we want to keep it audio-server agnostic (there a a few other competitors to forked-daapd that we could also settle for).
