### ISSUE TITLE
Cant play any music when connected with iPad

### ISSUE THREAD

**Issue by VoxelTek** [balenalabs/balena-sound#23]
Whenever I boot the RPi and i see the log on the dashboard, this comes up:
`amixer: Unable to find simple control 'PCM',0`
i ignore it, as i do not think it will affect anything. I connect my iPad(or whatever device i am using) to the bluetooth and start playing some music. when i hear nothing, i go back to the log and see a lot of errors in there. the errors are:
```
/usr/bin/bluealsa-aplay: Couldn't open PCM: No such device

ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave

/usr/bin/bluealsa: SBC decoding error: No such file or directory

/usr/bin/bluealsa: Missing RTP packet: 4157 != 4156

```
 however, when i press pause on my ipad, the errors stop spitting out. all this time, there is absolutely no sound coming through the speakers, which i have tested. i really want to be able to use bluetooth with these speakers. please resolve this issue immediately.

From,
VoxelTek

**Comment by AlexProgrammerDE** [comment]
Which Pi are you using?

**Comment by VoxelTek** [comment]
I am using a Raspberry Pi 3B

**Comment by AlexProgrammerDE** [comment]
Have you tried reinstalling?

**Comment by VoxelTek** [comment]
Yes, multiple times. I have had the same error every time.

**Comment by AlexProgrammerDE** [comment]
Are you using the on board jack or a external sound card (USB, GPIO, etc.)?

**Comment by VoxelTek** [comment]
The on board jack.

**Comment by AlexProgrammerDE** [comment]
Try it please with:

`apt-get update && apt-get install --reinstall alsa-utils`

(In the bluetooth-audio container which is aviable at the cloud dashboard)

**Comment by VoxelTek** [comment]
Ok thanks

**Comment by AlexProgrammerDE** [comment]
Try it please with balenaOS 2.38.0+rev1 production this was a solution in #47 which had the same errors.

**Comment by AlexProgrammerDE** [comment]
@VoxelTek Did it help?

**Comment by VoxelTek** [comment]
Unfortunately, I have been too busy to try any of these solutions. I should be able to try them in 2 days time.

**Comment by AlexProgrammerDE** [comment]
Ok

**Comment by tmigone** [comment]
Hey @VoxelTek, whenever you have time, please feel free to try again with the latest version of balenaOS as Alex suggested. Cheers!

**Comment by willenglishiv** [comment]
I have a fresh install of this on a raspberry pi 3B and I'm experiencing the same issue.  I connected my galaxy phone through spotify connect and bluetooth and nothing comes out of the audio port.  same error logs.

**Comment by AlexProgrammerDE** [comment]
@willenglishiv Can you give me the health test reports please?  You can get it at the bottom left of the dashboard.

**Comment by chrisys** [comment]
@willenglishiv  @VoxelTek can you confirm you are not using the 64-bit OS and give it a try with the latest version. If the issue still persists after this please feel free to reopen the ticket.
