### ISSUE TITLE
Trouble setting up Balena Sound services

### ISSUE THREAD

**Issue by Javilatte** [balenalabs/balena-sound#236]
When I access my Balena dashboard I can't see the services part where you activate or deactivate Airdrop, Bluetooth...
It just does not appear  (I've been following [the official tutorial](https://www.balena.io/blog/turn-your-old-speakers-or-hi-fi-into-bluetooth-receivers-using-only-a-raspberry-pi/)). 
Can anyone help me?

**Comment by tmigone** [comment]
hey @Javilatte, do you mean you can't see the section or that the section has an empty container list? If the section is empty it might be that you didn't deploy the application yet, maybe you skipped a step?

In any case, our forums (https://forums.balena.io/) are a much better place for this type of support questions. We are very active with support in our forums which is handled by the same engineers that build the balena products. So I suggest you post there if you don't manage to solve your problem.
