### ISSUE TITLE
Plugin: Airplay

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#242]
Convert image to use pulseaudio backend if possible. According to docs [here](https://github.com/mikebrady/shairport-sync#what-else) it has pulseaudio backend, though it might not be included on the apt-get package, so maybe we need to build from source?

**Comment by minix1234** [comment]
Mr. Brady has done some significant work creating a common docker image for shairport-sync. please see docker file at https://hub.docker.com/r/mikebrady/shairport-sync/dockerfile

**Comment by minix1234** [comment]
ps. the Debian package is very much outdated

**Comment by AlexProgrammerDE** [comment]
@minix1234 what do you mean with "outdated"? Does the team no longer maintain the project or are they just not publishing the code? @tmigone if thats the case we should maybe build it ourselfes.

**Comment by minix1234** [comment]
the Debian package repository is at revision 3.2.2 (October 2018) while current GitHub release is 3.3.7.  I believe Chris boot was maintaining the Debian package/git repository.  it has since been stale.

**Comment by minix1234** [comment]
and just for clarification I'm not sure why that's the case.  I see Mr boot has been doing work on the Debian version of the repository in late 2019.  but the packaged version of the application is still 3.2.2.

**Comment by tmigone** [comment]
@minix1234 do you know if the the docker image works across the entire raspberry pi family of devices?

**Comment by minix1234** [comment]
Evening,

It should yes.  I have a version that is working very well on RP zero.  so I assume it works with all the rest.

check my forked Belena-Sound repository's Airplay folder.  the docker image is generic but I have modified the start script to suit my needs.

**Comment by tmigone** [comment]
Hey, thanks for the information. I'll take a look but this sounds like a great idea. Thanks for bringing it up!

**Comment by AlexProgrammerDE** [comment]
Seems all done here
