### ISSUE TITLE
Plugin: UPnP

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#243]
Convert image to use pulseaudio backend if possible. According to docs [here](https://github.com/hzeller/gmrender-resurrect/blob/master/INSTALL.md) it has PA a backend

**Comment by AlexProgrammerDE** [comment]
yes it has. Im doing it rn. Its a simple change. We need to install the pulseaudio gstreamer package instead of als package.

**Comment by AlexProgrammerDE** [comment]
I pushed the code. I still get no output at both services. I will take a look at airplay later.

**Comment by tmigone** [comment]
works great! 👍
