### ISSUE TITLE
Plugins: new ones!

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#247]
Would be nice to have a few more plugins (one or two). Roonbridge sounds like an easy one since there is a PR already.

**Comment by tmigone** [comment]
balenaSound 3.0 will have:
- AirPlay
- Spotify
- UPnP
- Bluetooth
- Soundcard input via USB/audio jack/etc

**Comment by AlexProgrammerDE** [comment]
ok lets add more when the release rolled out. I think the community will like plugins. 👍
