### ISSUE TITLE
Add support for Beyerdynamic A200p DAC

### ISSUE THREAD

**Issue by arashrh1** [balenalabs/balena-sound#258]
Hi :),
Im using balena-sound and I've got a Beyerdynamic A200p which is not officially supported.
It would be great if you could add support for this DAC. 🙏🙏🙏

**Comment by tmigone** [comment]
Hi @arashrh1, as far as I can tell this is a USB DAC right? 
If so, balenaSound 2.x does not support it unfortunately, but the next major version (3.x) should! We don't have an ETA yet on when that will be ready but it's high on our priority list.

**Comment by tmigone** [comment]
Hey @arashrh1, with the release of balenaSound v3.0 USB soundcards should be supported out of the box. Let us know if you have trouble setting it up or have any other questions. Thanks!
