### ISSUE TITLE
balena-sound support for the Hifiberry DAC2 HD

### ISSUE THREAD

**Issue by ehowell46** [balenalabs/balena-sound#279]
The Hifiberry DAC2 HD was recently released, and is not on the balena sound configuration compatibility list. Would it be possible to add support for this device?

https://sound.balenalabs.io/docs/dac-configuration/

 https://www.hifiberry.com/shop/boards/hifiberry-dac2-hd/

Thank you!

Erik

**Comment by doronbehar** [comment]
The balena sound project supports any dac that (usually Raspberry Pis) support. You will probably get along with setting the correct device tree overlay variable - in your fleet / device configuration. I got my Piano DAC working without surprise although it was not listed on that list.

Perhaps the issue isn't the lack of support, but the lack of documentation :).

**Comment by ehowell46** [comment]
I've tried using the "hifiberry-dac" and "hifiberry-dacplus" overlays, but was unable to get them to work. I'll continue to try the remaining overlays available on the list.

**Comment by doronbehar** [comment]
You should use `hifiberry-dacplushd` according to this: https://www.hifiberry.com/docs/data-sheets/datasheet-dac-hd/ .

**Comment by ehowell46** [comment]
That worked! Thank you for your help with this! Very much appreciated. I will make sure to reference the product datasheet on Hifiberry's product page for dtoverlay information in the future.

**Comment by tmigone** [comment]
Thanks @doronbehar and @ehowell46 for the testing. I'll add the DAC to the list. Cheers!
