### ISSUE TITLE
Flash BalenaOS to MicroSD

### ISSUE THREAD

**Issue by nwhit24** [balenalabs/balena-sound#281]
**Describe the problem**
Attempted to Flash BalenaOS for Raspberry Pi 4 on a 32GB Samsung EVO MicroSD using balenaEtcher. The Etcher told me the file is corrupted. I deleted the zip file and downloaded again, still "corrupted".

**To Reproduce**
1. Download BalenaOS for Raspberry Pi 4
2. Open balenaEtcher
3. Select file, select device, flash

**Expected behavior**
Expected the OS to be downloaded.

**Screenshots**
![BalenaEtcherError_RaspberryPi4](https://user-images.githubusercontent.com/45721259/93025447-e00aa800-f5b2-11ea-98ba-0feb85750e66.PNG)

**Device information**
 - Raspberry Pi 4B
 - Raspberry Pi 4
 - balenaOS v2.56.0+rev1

**Comment by tmigone** [comment]
Hi @nwhit24, this looks like a problem with balenaEtcher. At first sight it seems like that's a rather old version of etcher though I might be wrong. I suggest you re-post your problem at our forums: https://forums.balena.io/. We are very active in there and you'll get great support.
