### ISSUE TITLE
Raspberry Pi b+ 2014 (RPi2) won't boot

### ISSUE THREAD

**Issue by jesterino** [balenalabs/balena-sound#283]
Hello
I have 6 Rpi2 with Corepi and would love to migrate to BAlena Sound
After i create the application on Balena account and add a Rpi2 to it, i download all version newest and old of the image and flashed it with Eatcher, but Rpis won't boot. The green led flash 7 times.
Any suggest?
Thank you

**Comment by AlexProgrammerDE** [comment]
@jesterino hi! I think its some error code balenaOS wants to tell you. I don't know what it means, but i know where you should find better help: balenaForums https://forums.balena.io/ There are really active balena employers and they will help you. It doesn't seem related to balenaSound so i recommend you to ask there to balenaOS related help. I am going to close this issue for now. Feel free to open a new issue if you have any balenaSound related issues when you get the operating system working. Good luck! 👍
