### ISSUE TITLE
Ability to disable automatic master/client renegotiation

### ISSUE THREAD

**Issue by ChestersGarage** [balenalabs/balena-sound#288]
**Is your feature request related to a problem? Please describe.**
I would like to manually manage what clients are associated with each master on my fleet.  This allows me to have multiple different source streams running on different masters, and assigned to specific clients.  A standalone snapcast client is capable of assigning clients to servers manually.  But the automatic renegotiation of the masters foils those capabilities, and prevents multiple server streams.

**Describe the solution you'd like**
I'd like an environment variable that disables auto-renegotiation of masters and clients, so that I can manually assign clients to each master through the snapcast client.

**Additional context**
This would need to be an advanced feature, since the snapcast client is not easily obtained on all platforms, and is a rough UI, not meant for general usage.  The only platform that has an easy solution is Android, where the snapcast client is available as an app. 

The Snap.Net Windows client (Not installable by casual users)
![Snap Net (Windows snapclient)](https://user-images.githubusercontent.com/6581172/93378027-b64ebc80-f810-11ea-9972-68ddd50a9fb4.png)

The Android Snapcast client (Free on Google Play)
![Snapcast (Android snapcast client) 1](https://user-images.githubusercontent.com/6581172/93378043-bb137080-f810-11ea-9f4b-86bc3d668bae.jpg)

![Snapcast (Android snapcast client) 2](https://user-images.githubusercontent.com/6581172/93378056-bf3f8e00-f810-11ea-996b-0c7c9dafea9f.jpg)

**Comment by tmigone** [comment]
Hey @ChestersGarage, I just implemented an option that I think would work for this use case. Setting `SOUND_MULTIROOM_DISALLOW_UPDATES` will prevent a device from reconfiguring it's multiroom master whenever it receives an update from the fleet. Let me know if this helps!

**Comment by ChestersGarage** [comment]
@tmigone I just saw this.  I'll try it out and see how it goes.
