### ISSUE TITLE
Allo Boss DAC

### ISSUE THREAD

**Issue by johan489** [balenalabs/balena-sound#305]
Could you pretty please add ALLO BOSS DAC to the supported HAT's.
It is an fantastic DAC.

Thanks,

Johan

**Comment by tmigone** [comment]
Hey @johan489 is this the DAC? https://allo.com/sparky/boss-dac.html

**Comment by johan489** [comment]
Yes, that's it.

**Comment by tmigone** [comment]
Can you try following the [DAC configuration section](https://sound.balenalabs.io/docs/audio-interfaces/#dac-boards) with this value `allo-boss-dac-pcm512x-audio` for `BALENA_HOST_CONFIG_dtoverlay`? I think that's the correct one. Let me know if it works and I'll add it to the list.

**Comment by johan489** [comment]
I will try it out.

**Comment by tmigone** [comment]
If you already pushed the application you are going to have to re-push it because of this bug: #296. 
It should be fixed as of today but if you deployed your app yesterday then you need to re-reploy.

**Comment by johan489** [comment]
`That worked perfectly, case closed

Thanks!`
