### ISSUE TITLE
Balenablocks and balena-fin 

### ISSUE THREAD

**Issue by fuzzybear62** [balenalabs/balena-sound#309]
Abort when building for balena-fin:

[sound-supervisor]  Successfully built 2b57bcef9799
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: audio
[Error]                 Error: manifest for balenablocks/audio:fincm3 not found: manifest unknown: manifest unknown
[Error]               Service: bluetooth
[Error]                 Error: manifest for balenablocks/bluetooth:fincm3 not found: manifest unknown: manifest unknown
[Info]              Built on arm03
[Error]             Not deploying release.

remote: error: hook declined to update refs/heads/master
To git.balena-cloud.com:g_aldo_curinga/balena-sound.git
 ! [remote rejected] master -> master (hook declined)

**Comment by tmigone** [comment]
hey @fuzzybear62 thanks for reporting this. Looks like `balenablocks/audio` and `balenablocks/bluetooth` `fincm3` images were not published. I've published them now and it should be working. Thanks again.
