### ISSUE TITLE
docs broken 

### ISSUE THREAD

**Issue by sceptiq** [balenalabs/balena-sound#311]
https://sound.balenalabs.io/docs/

gives me

```
An internal error occured!

Please see the console for more details.
```

**Comment by SerialHacker** [comment]
Been like this for the entire weekend, what an unfortunate timing.

Hope it gets fixed soon!

**Comment by sceptiq** [comment]
https://github.com/balenalabs/balena-sound/tree/master/docs 

Is where I found what I was looking for ... :)

**Comment by tmigone** [comment]
Thanks guys for reporting this. We've been having some trouble with our docs site, should be solved now and hopefully won't be down again. 
As @sceptiq noted, the repo can be used as a workaround since it contains all the docs site info in the `docs` folder linked above.
