### ISSUE TITLE
Support for the Hifiberry Digi+ Pro 'DAC'

### ISSUE THREAD

**Issue by SerialHacker** [balenalabs/balena-sound#317]
Currently, only the Digi+ and not the Digi+ Pro is included in the list of supported DACs, Hifiberry recommended that i use the dtoverlay value 'hifiberry-digi-pro' which seems to be working to a great success.

I was wondering whether the Digi+ Pro is completely supported already? Or whether further coding should be added to fully support it?

**Comment by shawaj** [comment]
@SerialHacker yes we already have the overlay available in the balenaOS https://github.com/balena-os/balena-raspberrypi/blob/master/layers/meta-balena-raspberrypi/conf/layer.conf

So can you confirm the HiFiBerry Digi+ Pro is working nicely for you with the `hifiberry-digi-pro` overlay?

**Comment by tmigone** [comment]
Closing as the Digi+ Pro is now categorized as untested. See https://github.com/balenalabs/balena-sound/issues/439 and https://sound.balenalabs.io/docs/audio-interfaces#dac-boards
