### ISSUE TITLE
Can't find a liat od supoorted DACs

### ISSUE THREAD

**Issue by febs** [balenalabs/balena-sound#320]
I browsed the docs and could not find a list of supported DACs. I think that it should be a clickable link on the main README.md file; and the lack of it is pretty much an UX bug in my opinion... hence the "issue" I am filing. 

Thanks for caring,

**Comment by eiddor** [comment]
This list here isn't what you're looking for? https://sound.balenalabs.io/docs/audio-interfaces#dac-boards

**Comment by febs** [comment]
Yup, that really should be linked in the main page of the project (that is, README.md on github). I submitted a tiny PR for that. Thanks,
