### ISSUE TITLE
IQaudio Pi-DigiAMP+

### ISSUE THREAD

**Issue by SimonMellerin** [balenalabs/balena-sound#322]
Hi there,

First of all, thanks for your work, seems awesome ! :wink:

I’m trying to use balenaSound with a IQaudio Pi-DigiAMP+ and a RPI3 ,
I found the correct `BALENA_HOST_CONFIG_dtoverlay` value which is `iqaudio-dacplus,unmute_amp`

My DAC is correctly found. And the music is ok with spotify-connect.

But when I connect my phone through bluetooth and try to play sound, these errors appear in logs and I can't hear anything:

```
05.10.20 12:20:20 (+0200)  audio  W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 230.00 ms
05.10.20 12:20:31 (+0200)  audio  E: [bluetooth] a2dp-codec-sbc.c: SBC decoding error (-3)
05.10.20 12:20:31 (+0200)  audio  E: [bluetooth] module-bluez5-device.c: Decoding error

```

It seems that bluetooth problem is common with RPi3 so I'm gonna buy a dongle.

**But you can add IQaudio Pi-DigiAMP+ to your list of supported devices !**

Thanks,
Simon

**Comment by shawaj** [comment]
Added in #376 

Thanks @SimonMellerin
