### ISSUE TITLE
Alsa Settings Reset

### ISSUE THREAD

**Issue by ghost** [balenalabs/balena-sound#33]
Hi Chris, I am really enjoying balena sound. I installed it using the dockerfile(no balena OS). I also switched to ethernet as I thought it will improve my LAN speeds as I am using the Pi as a small NAS and will improve Bluetooth functionality(besides Cypress fix). Everything is working great but the volume setting is resetting.

I am increasing the volume through alsamixer and storing the settings using alsactl, but I still see the volume reset to 36%. Even when I increase the audio in my phone, I still see no change.

Thank you for your wonderful project! I have searched for many days for something like this. I really like the docker thing. Spin up and spin down!

**Comment by AlexProgrammerDE** [comment]
@capriciousduck You can use the function added by chrisys with which you can set the system output of the bluetooth music container. Add to the template:

> ENV SYSTEM_OUTPUT_VOLUME 100

And replace 100 with your wished Volume.
Also you need to delete the following line from start.sh:

>

**Comment by AlexProgrammerDE** [comment]
@capriciousduck Has it worked?

**Comment by capriciousduck** [comment]
No. It is still resetting.

**Comment by capriciousduck** [comment]
I am using Dietpi with Docker installed.

**Comment by AlexProgrammerDE** [comment]
In https://dietpi.com/phpbb/viewtopic.php?t=1508 was the solution: sudo

**Comment by capriciousduck** [comment]
I am a root user. I am using the latest image of dietpi. It only has root
user by default. So all the commands I run, will run as root.

**Comment by AlexProgrammerDE** [comment]
How about this: https://community.roonlabs.com/t/save-last-volume-level-with-dietpi/47635

**Comment by capriciousduck** [comment]
Now I see that the volume is resetting every time I connect and disconnect bluetooth. After connecting to my bluetooth device, I always have less volume output in Pi. So I set to desired volume using alsactl. After I play music  for a while and disconnect and then connect again at some other time the volume is resetting.

I set the volume env variable too. But that doesn't work.

**Comment by AlexProgrammerDE** [comment]
How about changing bluetooth-udev everytime you connect and disconnect your specific commands are running.

**Comment by capriciousduck** [comment]
I don't know much about Bluetooth config. Can you please tell me exactly
what I should do?

**Comment by AlexProgrammerDE** [comment]
So the bluetooth-udev file is a bash script, which runs specific code in a specific case appears. You will see it when you edit it. :smile_cat:

**Comment by AlexProgrammerDE** [comment]
There can you add at the end the from you used commands. I dont know if it works. Just try.

**Comment by AlexProgrammerDE** [comment]
And did it work?

**Comment by tmigone** [comment]
Possibly related to #78

**Comment by AlexProgrammerDE** [comment]
Closing, because the account got deleted and this issue got possibly resolved by #129 .
