### ISSUE TITLE
WM8960_Audio_HAT DAC board support

### ISSUE THREAD

**Issue by simonvanhove** [balenalabs/balena-sound#331]
Hi,

is it possible to provide support for WM8960_Audio_HAT from Waveshare?
Here is their manual.

https://www.waveshare.com/w/upload/5/54/WM8960_Audio_HAT_User_Manual_EN.pdf

Greets,

Simon

**Comment by shawaj** [comment]
Duplicate of #264

**Comment by AlexProgrammerDE** [comment]
@shawaj may you tell me how to set a issue to a duplicate? If so please let me know.

**Comment by shawaj** [comment]
@AlexProgrammerDE hmm I am not actually sure how you do it. All I did was put a comment saying `Duplicate of ...` and it seemed to automatically set it like that?

It seems to be a standard feature of GitHub according to this doc - https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests

**Comment by shawaj** [comment]
Getting closer https://github.com/balenalabs/balena-sound/issues/264#issuecomment-756428272
