### ISSUE TITLE
SOUND_DEVICE_NAME doesn't change device name

### ISSUE THREAD

**Issue by jgottlander** [balenalabs/balena-sound#341]
**Describe the problem**
Setting SOUND_DEVICE_NAME to custom variable doesn't change device name.
BLUETOOTH_DEVICE_NAME works as intended.

**To Reproduce**
1. Set SOUND_DEVICE_NAME to custom variable.
2. Spotify Connect and Airplay speaker still has default name, in my case "balenaSound Spotify/Airplay 2d8c"

**Expected behavior**
Setting SOUND_DEVICE_NAME to custom variable, should change Spotify and Airplay speaker to custom variable.

**Screenshots**
![bild](https://user-images.githubusercontent.com/1482512/97753796-a526ea00-1af6-11eb-8e04-de2a696c545a.png)
![bild](https://user-images.githubusercontent.com/1482512/97753695-790b6900-1af6-11eb-85a1-61ee3417512e.png)

**Device information**
 - Board (hardware info): Raspberry Pi 3B
 - Device type (as seen in balenaCloud): Raspberry Pi 3
 - balenaOS version: balenaOS 2.58.3+rev1
 - DAC: HifiBerry DAC+

**Comment by eiddor** [comment]
Interesting - SOUND_DEVICE_NAME does change the Spotify Connect name for me, but not the Bluetooth Name.

![image](https://user-images.githubusercontent.com/7586731/97753142-4a27cf80-1ac3-11eb-82f1-f4f08197e325.png)

![image](https://user-images.githubusercontent.com/7586731/97753117-4005d100-1ac3-11eb-83af-744b82b1db96.png)

**Comment by jgottlander** [comment]
It worked perfectly before I upgraded to balenaOS 2.58, it was 2.53/2.54 if I remember correctly.
I've now upgraded to 2.60.1+rev1 but the problem persists.

**Comment by TwoTenPvP** [comment]
> Interesting - SOUND_DEVICE_NAME does change the Spotify Connect name for me, but not the Bluetooth Name.
> 
> ![image](https://user-images.githubusercontent.com/7586731/97753142-4a27cf80-1ac3-11eb-82f1-f4f08197e325.png)
> 
> ![image](https://user-images.githubusercontent.com/7586731/97753117-4005d100-1ac3-11eb-83af-744b82b1db96.png)

Bluetooth name has it's own property.  ``BLUETOOTH_DEVICE_NAME``

**Comment by AlexProgrammerDE** [comment]
As far as I remember spotify has in 3.0 now its own property. You may find the info you need in the docs.

**Comment by jgottlander** [comment]
I checked raspotify's documentation, and they use DEVICE_NAME as variable name, and I tried using only DEVICE_NAME, and it indeed changes the Spotify device name. So there seems to be a need for three different variables to cover all custom names for soundbalena.

**Comment by vordenken** [comment]
I can confirm this, DEVICE_NAME changes the Spotify Connect as well as the AirPlay name for me, SOUND_DEVICE_NAME does nothing. This should probably be changed in the documentation.
