### ISSUE TITLE
Connected but not playing any sound

### ISSUE THREAD

**Issue by bmugle0** [balenalabs/balena-sound#343]
I have been trying to use it but even though my computer says it is connected it does not play any sound, and sometimes it just unconnects. When I try to play music, it says on the balena dash board: SBC decoding error (-2) and then the next row it says decoding error.

**Comment by shawaj** [comment]
@bmugle0 how are you trying to play the sound? Is it Bluetooth or some other method?

And what file format are you trying to play?

**Comment by AlexProgrammerDE** [comment]
This is related to Bluetooth and already reported. Duplicate of #62
