### ISSUE TITLE
Add AUDIOPHONICS I-Sabre DAC ES9023 Support (RBP 1 B+)

### ISSUE THREAD

**Issue by mwebm** [balenalabs/balena-sound#345]
Hello,

I am currently using the balena system for playing sound on my HIFI system with a RBP B+ v1.2, and it sounds nice thank you !
Now I would like to use my DAC for a better audio quality. Could you please add support for the following reference (which is currently not on the list in documentation) ?

https://www.audiophonics.fr/fr/dac-et-interfaces-pour-raspberry-pi/audiophonics-i-sabre-dac-es9023-tcxo-raspberry-pi-a-b-20-i2s-p-9978.html

Thanks
Maxime W.

**Comment by shawaj** [comment]
@mwebm it should work with the dtoverlay set to `hifiberry-dac`

Can you try it and let us know if it works ok for you?
