### ISSUE TITLE
Airplay sound is too low

### ISSUE THREAD

**Issue by SigmaReloaded** [balenalabs/balena-sound#346]
hi guys! I'm already using Raspberry4 4gb with balena sound, when i use airplay from my Iphone to reproduce music from spotify, slace volumen it's not working very well and output volumen its too low. I'm trying with this configs

Device Variables config
![image](https://user-images.githubusercontent.com/68396278/98564413-5b6a9c00-227a-11eb-8c86-35b902683219.png)

![image](https://user-images.githubusercontent.com/68396278/98564474-6cb3a880-227a-11eb-876b-5772f40e2ab6.png)

Any suggestions?

**Comment by parallelbgls** [comment]
Seems to have same problem with RP4, I have to turn all devices to maximum to get suitable volumn. I think max volumn is too low.

**Comment by tmigone** [comment]
Hey can you try reproduce this with latest balenaSound version 3.8.9? Feel free to re-open this issue if the problem persists. Thanks!
