### ISSUE TITLE
unable to connect bluetooth. 

### ISSUE THREAD

**Issue by BOOM3r** [balenalabs/balena-sound#351]
I've followed the directions on the project, and I feel like I've done pretty good for being out of my normal scope. But I can't seem to find it to connect to it via bluetooth. and it's not listed as a service either. Not sure if that was something that needed to get listed in the build? 
I only have one service listed on the device "Main"?
A few shots I've been able to find have a whole slew of services. I'm not sure what I've done wrong. 

help

**Comment by tmigone** [comment]
Hi @BOOM3r, I know it's been a while but it looks like your project was not deployed successfully to your device (you should have a lot more services listed). If you are still interested in getting it to run and haven't managed to do so I suggest you visit our forums (https://forums.balena.io/). We are pretty active in there and will be able to assist you deploying projects and general troubleshooting in a much more prompt way.
