### ISSUE TITLE
Bluetooth connection - cannot manage sound level

### ISSUE THREAD

**Issue by laurentsinaretty** [balenalabs/balena-sound#373]
When connected to bluetooth, I cannot manage to level the sound.
On Iphone 7 : 
Bluetooth connected
Play a song 
Push the buttons to level the sound and nothing happens.
It works with airplay but not with bluetooth. Can you help me?

On rasperry pi Zero W 1.1
with hifiberry-dac

**Comment by eiddor** [comment]
This is covered by issue #300 

The workaround is posted [here](https://github.com/balenalabs/balena-sound/issues/300#issuecomment-722444790).

**Comment by tmigone** [comment]
Closing as it's a duplicate of #300.
