### ISSUE TITLE
UPNP : All servers use the same default UUID

### ISSUE THREAD

**Issue by JodyGoldberg** [balenalabs/balena-sound#380]
When running multiple upnp servers on the same network (e.g. in standalone mode) only one is visible to clients.   Which server is visible is a race condition.   Checking the gmediarender code clarifies that there is a default hard coded id when none is specified.

[https://github.com/hzeller/gmrender-resurrect/blob/master/src/main.c#L83](url)

**Comment by tmigone** [comment]
Fixed by #381. 
balenaSound v3.4.6
