### ISSUE TITLE
Add Infineon / Merus Audio amp board

### ISSUE THREAD

**Issue by shawaj** [balenalabs/balena-sound#383]
The [Merus Audio Amp pHAT by Infineon](https://www.infineon.com/cms/en/product/evaluation-boards/kit_40w_amp_hat_zw/) is a super efficient amplifier for Raspberry Pi (can output 40W peak using just the 2.5A Pi power supply!). It uses the [MA12070P](https://www.infineon.com/cms/en/product/power/class-d-audio-amplifier-ic/integrated-class-d-audio-amplifier-ics/ma12070p/) chip and the `merus-amp.dtbo` device tree overlay.

Working on a PR - but just adding this to track progress/info.

```
root@2ac79ccab9fe:/usr/src# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: dac [snd_rpi_merus_amp], device 0: Merus Audio Amp ma120x0p-amp-0 [Merus Audio Amp ma120x0p-amp-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

```
root@2ac79ccab9fe:/usr/src# cat /proc/asound/cards
 0 [dac            ]: RPi-simple - snd_rpi_merus_amp
                      snd_rpi_merus_amp
```

```
root@2ac79ccab9fe:/usr/src# cat /proc/asound/modules
 0 snd_soc_rpi_simple_soundcard
```

```
root@2ac79ccab9fe:/usr/src# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=dac,DEV=0
    snd_rpi_merus_amp, Merus Audio Amp ma120x0p-amp-0
    Direct hardware device without any conversions
plughw:CARD=dac,DEV=0
    snd_rpi_merus_amp, Merus Audio Amp ma120x0p-amp-0
    Hardware device with all software conversions
sysdefault:CARD=dac
    snd_rpi_merus_amp, Merus Audio Amp ma120x0p-amp-0
    Default Audio Device
dmix:CARD=dac,DEV=0
    snd_rpi_merus_amp, Merus Audio Amp ma120x0p-amp-0
    Direct sample mixing device
usbstream:CARD=dac
    snd_rpi_merus_amp
    USB Stream Output
```

**Comment by shawaj** [comment]
[Infineon-MA12070P-DS-v01_00-EN.pdf](https://github.com/balenalabs/balena-sound/files/5742607/Infineon-MA12070P-DS-v01_00-EN.pdf)

[Infineon-KIT_40W_AMP_HAT_ZW-UserManual-v01_00-EN.pdf](https://github.com/balenalabs/balena-sound/files/5742608/Infineon-KIT_40W_AMP_HAT_ZW-UserManual-v01_00-EN.pdf)

[Infineon-KIT_40W_AMP_HAT_ZW-ApplicationNotes-v01_00-EN.pdf](https://github.com/balenalabs/balena-sound/files/5742611/Infineon-KIT_40W_AMP_HAT_ZW-ApplicationNotes-v01_00-EN.pdf)

[Infineon / Merus GitHub page](https://github.com/Infineon/merus-audio-amp-hat-zw)

**Comment by shawaj** [comment]
Was having the same issue as described [here](https://github.com/Infineon/merus-audio-amp-hat-zw/issues/4#issuecomment-724426136)

Basically - the resolution is to edit the dtparams to be:
`"i2c_arm=on","spi=off","audio=off"`

As SPI pin CE0 (pin 24 / GPIO8) is attached to MSEL0 it causes issues if the SPI interface on the Pi is on.

![image](https://user-images.githubusercontent.com/3359418/103144701-d2be9700-4725-11eb-8177-d04e6b778665.png)

Also for reference see https://github.com/Infineon/merus-audio-amp-hat-zw/issues/4 and https://github.com/raspberrypi/linux/pull/4027

**Comment by shawaj** [comment]
Added a PR on balena-raspberrypi repo to pull in the merus-amp device tree overlay to balenaOS - https://github.com/balena-os/balena-raspberrypi/pull/585 (as well as a few other audio related ones such as the IQaudIO codec)

**Comment by tmigone** [comment]
Board now supported in balenaOS.
Superceded by https://github.com/balenalabs/balena-sound/issues/439
