### ISSUE TITLE
Raspberry Pi 4 not detecting SD Card with balenaOS

### ISSUE THREAD

**Issue by willtherussian** [balenalabs/balena-sound#400]
I've flashed it many times and still doesn't work. I reflashed the raspberry os back on and that works so the SD card is fine.

**Comment by shawaj** [comment]
@willtherussian where are you getting the image for balenaOS?

**Comment by willtherussian** [comment]
I dont know if this is what you meant but from here 
https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/balenalabs/balena-sound&d_id=176c68607a81cc-0ad06bb9f71268-c791039-1fa400-176c68607a97ff

**Comment by willtherussian** [comment]
@shawaj 

> I dont know if this is what you meant but from here
> https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/balenalabs/balena-sound&d_id=176c68607a81cc-0ad06bb9f71268-c791039-1fa400-176c68607a97ff

**Comment by shawaj** [comment]
Ok and on that screen do you select the Raspberry Pi 4 as the device type?

I have it working fine on a Pi 4, so ideally just need to have the exact steps you are following to try and reproduce the issue.

Also how do you know it isn't working?

**Comment by willtherussian** [comment]
Yes I select the Raspberry Pi 4 as the device type.

I can tell its not working as the ACT led doesn't light up and tried hooking it up to a monitor and there was nothing detected.

**Comment by shawaj** [comment]
Have you tried downloading the image again? As it sounds like it maybe got corrupted on download or something like that.

**Comment by willtherussian** [comment]
Yes, I've tried about 4 times

**Comment by shawaj** [comment]
I have just tried this again on my end from scratch and it works. So there must be something you are not doing right.

Can you download the image from here and see if that boots to a splash screen? https://www.balena.io/os/

**Comment by willtherussian** [comment]
I tried that and it doesn't work either

**Comment by tmigone** [comment]
Hey @willtherussian, if you are still having trouble I suggest you post on our forums (https://forums.balena.io/). From experience this can be caused by many things: a problem with the SD card, the OS image you downloaded, network settings, etc. We have multiple support agents and community members on our forums that will be able to promptly assist you.
