### ISSUE TITLE
Wifi setup fails

### ISSUE THREAD

**Issue by rtcpersonal2020** [balenalabs/balena-sound#403]
**Describe the problem**
Wifi setup fails.  RPI3 will not connect to simple wifi using WAP credentials after downloading an booting the "custom" image. 

Lots of wasted time and effort.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information**
 - Board (hardware info): [e.g. Raspberry Pi 3B+]
 - Device type (as seen in balenaCloud): [e.g. Raspberry Pi 3 (using 64bit OS)]
 - balenaOS version: [e.g. balenaOS v2.47.0+rev1]

**Additional context**

**Comment by tmigone** [comment]
Hey @rtcpersonal2020, thanks for trying out balenaSound. If you are still having trouble with your board connecting to WiFi I suggest you post on our forums (https://forums.balena.io/), this is very likely not related to balenaSound. We are very active on the forums with multiple support agents that will help you out if needed.

**Comment by rtcpersonal2020** [comment]
The volumio distro worked first time, no modifications.  It's your image.



-------
On Tue, 19 Jan 2021 06:46:12 -0800, Tomás Migone  
<notifications@github.com> wrote:

> Hey @rtcpersonal2020, thanks for trying out balenaSound. If you are  
> still having trouble with your board connecting to WiFi I suggest you  
> post on our forums (https://forums.balena.io/), this is very likely not  
> related to balenaSound. We are very active on the forums with multiple  
> support agents that will help you out if needed.
>


-- 
Using Opera's mail client: http://www.opera.com/mail/
