### ISSUE TITLE
Project site appears behind on version

### ISSUE THREAD

**Issue by ChestersGarage** [balenalabs/balena-sound#408]
**Describe the problem**
Project and documentation site is showing version 3.4.2, but Github shows 3.4.7.  Seems like an update is needed there.  :)

https://sound.balenalabs.io/

**Comment by tmigone** [comment]
@iamsolankiamit can you help us out here? Looks like landrbot is producing the preview websites fine but the production one is not being updated on merge.

**Comment by tmigone** [comment]
Fixed!
