### ISSUE TITLE
New DAC support for IQaudio DigiAmp+

### ISSUE THREAD

**Issue by TraceyWiedmeyer** [balenalabs/balena-sound#417]
Looking at using this DAC with Pi3/4, has decent AMP power and can use with passive wired speakers.

https://www.pishop.us/product/iqaudio-digiamp/?src=raspberrypi

**Comment by tmigone** [comment]
Superseded by https://github.com/balenalabs/balena-sound/issues/439

Please refer to linked issue for instructions if you want to help testing.
