### ISSUE TITLE
It would be great to share the offline music (CD, vynil, etc.) played on one of my audio systems with the others through the balena sound ecosystem. However, Raspberry Pi 4 or the DACs available do not have a line in. It could be solved by using a USB line in module. Would it be possible to add Balena Sound a feature that could share the music fed to it on one of the devices to the others?

### ISSUE THREAD

**Issue by Szubszidiaritas** [balenalabs/balena-sound#418]
Excuse me if this feature exists already, I did not find it.

**Comment by samaero** [comment]
This exists via the experimental variable SOUND_ENABLE_SOUNDCARD_INPUT. Connect a USB soundcard with inputs to your master device, connect your offline device (CD player, record player, etc.) to the soundcard's inputs, create the above variable on the device, and you should be able to stream your offline music source to the others units.

**Comment by Szubszidiaritas** [comment]
Thank you for your kind help!
