### ISSUE TITLE
Sound not outputting through other devices configured on network

### ISSUE THREAD

**Issue by sgupta40** [balenalabs/balena-sound#428]
I followed all instructions encased within this resource: https://www.balena.io/blog/turn-your-old-speakers-or-hi-fi-into-bluetooth-receivers-using-only-a-raspberry-pi/#hardwarerequired

and also this resource: https://www.balena.io/blog/diy-raspberry-pi-multi-room-audio-system/

I have successfully been able to view both devices online in my dashboard, however, when I play music to one via Bluetooth, I can hear sound from that device, but it is not playing to my other device. I currently have two Raspberry pi 3B+ configured. I am also using the auxiliary port built into the pis for sound output. All services are running, I am just not able to achieve the "multiroom" functionality.

**Comment by gik758** [comment]
I am running into the same problem. Did you solve it?
