### ISSUE TITLE
Add DAC to supported list

### ISSUE THREAD

**Issue by donnachiege** [balenalabs/balena-sound#433]
Hi, I'd like to use the DACBerry AMP+ with Balena Sound - is it possible to get it added to the Supported List, please?

https://www.osaelectronics.com/product/dacberry-amp-plus/

Thank you!
Glen

**Comment by tmigone** [comment]
Superseded by https://github.com/balenalabs/balena-sound/issues/439. 
Support for this board should be in place already, if you want to test it please follow [this](https://sound.balenalabs.io/docs/audio-interfaces#dac-boards) guide with `dtoverlay=hifiberry-dacplus`.
