### ISSUE TITLE
Add support for Suptronics x920 DAC

### ISSUE THREAD

**Issue by tbard1** [balenalabs/balena-sound#438]
Hi there

Could you please add support for this DAC ?
http://www.suptronics.com/miniPCkits/x920.html

Thanks!

**Comment by tmigone** [comment]
Superseded by #439 
I believe this board is supported already, can you try following [this](https://sound.balenalabs.io/docs/audio-interfaces#dac-boards) guide with `dtoverlay=iqaudio-dacplus`?

**Comment by tmigone** [comment]
Also, I'm closing the issue because going forward we will use #439 to centralize DAC requests. Please refer to that issue. If you have trouble or if you want to confirm this dtoverlay works feel free to add a comment over there. Thanks!
