### ISSUE TITLE
sound with  bluetooth  streaming is crackling 

### ISSUE THREAD

**Issue by ejannett** [balenalabs/balena-sound#440]
Hi ,

my multi-room fleet has two boards

the "master" node is connected using ethernet 
Raspberry Pi 3B (using 64bit OS), host os version balenaOS 2.65.0+rev1 , supervisor version 12.5.6

the "slave" node is using WIFI
Raspberry Pi 3 , host os version balenaOS 2.72.0+rev1, supervisor version 12.5.6

I cannot stream music to none of these devices using bluetooth  because the sound is really bad and cracklying.
I've seen many posts accusing the use of WIFI and bluetooth at the same time. This do not seems to be my case 
as streaming on the one using wired network suffer the same. 
This is not an issue related to my DACs as when using airplay , the sound is just fine.

any help would be appreciated
regards 
EJ

**Comment by tmigone** [comment]
Hey can you try reproduce this with latest balenaSound version 3.8.9? Feel free to re-open this issue if the problem persists. Thanks!
