### ISSUE TITLE
No sound volume control

### ISSUE THREAD

**Issue by Qu-Bi** [balenalabs/balena-sound#443]
When I connect via UPnP I can control volume, but when I connecting via Bluetooth I can't control volume.

**Comment by JaragonCR** [comment]
Is this a duplicate of https://github.com/balenalabs/balena-sound/issues/300 ?

I fixed mine (S21 Client) with the suggestion there

mount -o remount,rw /
systemctl edit --full bluetooth

edit to add the --plugin in this line

ExecStart=/usr/libexec/bluetooth/bluetoothd --experimental --plugin=a2dp

Save
Reboot

**Comment by tmigone** [comment]
Yup duplicate of #300.
