### ISSUE TITLE
Airplay refuses to run - pa context error

### ISSUE THREAD

**Issue by AliMickey** [balenalabs/balena-sound#463]
**Describe the problem**
![image](https://user-images.githubusercontent.com/60691199/120978694-18dd5380-c7b8-11eb-8dfc-3f3156c9946f.png)

**To Reproduce**
1. Clone the git
2. Adjust Dockerfile parameters for device type.
![image](https://user-images.githubusercontent.com/60691199/120978811-37434f00-c7b8-11eb-92ef-24b47f660d4d.png)
3. docker-compose up -d

Spotify works with no problems. 

**Expected behavior**
Airplay works

**Device information**
 - Board  Raspberry Pi 3
 - Device type: e.g. Raspberry Pi 3 running Raspbian

**Comment by TutosJuegosFree** [comment]
I have the same problem with a raspberry pi 3b+, the only way I found to solve it is to restart the service every time the computer boots up

**Comment by tmigone** [comment]
Fixed in v3.6.11. For details see https://github.com/balenalabs/balena-sound/pull/508
