### ISSUE TITLE
No more audio and "[Fatal] (Snapclient) Exception: No audio player support for: pulse" since latest release

### ISSUE THREAD

**Issue by xvisor16** [balenalabs/balena-sound#475]
Since the latest release the Multiroom-client continuously exits and restarts and keeps repeating this. No audio comes from my pi's anymore while spotify is playing.
I run dac's (hifiberry_plus) on my pi's and they have always worked like a charm.

24.06.21 17:34:12 (+0200) Restarting service 'multiroom-client sha256:ea0ad49dcbd0000cc7d39ace43811e18c9fc9147a9ced7f42442f89a0280c5fa'
24.06.21 17:34:11 (+0200)  multiroom-client  
24.06.21 17:34:11 (+0200)  multiroom-client  --- Multiroom ---
24.06.21 17:34:11 (+0200)  multiroom-client  Starting multiroom service with settings:
24.06.21 17:34:11 (+0200)  multiroom-client  - Mode: server
24.06.21 17:34:11 (+0200)  multiroom-client  - Snapcast version: v0.25.0
24.06.21 17:34:11 (+0200)  multiroom-client  Starting multi-room client...
24.06.21 17:34:11 (+0200)  multiroom-client  - balenaSound mode: MULTI_ROOM
24.06.21 17:34:11 (+0200)  multiroom-client  - Target snapcast server: 192.168.68.153
24.06.21 17:34:11 (+0200)  multiroom-client  2021-06-24 15-34-11.963 [Error] (Snapclient) PCM device "default" not found
24.06.21 17:34:11 (+0200)  multiroom-client  metadata:{"STREAM":"balenaSound"}
24.06.21 17:34:11 (+0200)  multiroom-client  2021-06-24 15-34-11.984 [Fatal] (Snapclient) Exception: No audio player support for: pulse
24.06.21 17:34:11 (+0200)  multiroom-server  2021-06-24 15-34-11.984 [Error] (StreamSessionTCP) Error reading message header of length 0: End of file
24.06.21 17:34:14 (+0200) Service exited 'multiroom-client sha256:ea0ad49dcbd0000cc7d39ace43811e18c9fc9147a9ced7f42442f89a0280c5fa'

My devices are: Raspberry Pi 3B+
 - Device type (as seen in balenaCloud): [Raspberry Pi 3]
 - balenaOS version: [balenaOS v2.80.3+rev1]
 - Running hifiberry_dacplus (either the AMP2 or the DAC+)
 - One of the 4 pi's just uses the jack output but experiences the same messages.

**Comment by tmigone** [comment]
Hey @xvisor16 thanks for reporting this was fixed on v3.6.7
