### ISSUE TITLE
I can't install tails with BalenaEtcher

### ISSUE THREAD

**Issue by Ryan5013** [balenalabs/balena-sound#486]
Every time I select tails then select target and then hit flash it asks for a password. it says balenaEtcher wants to make changes. Type your password to allow this. What is the password for this to work???

**Comment by eiddor** [comment]
I'm not sure what tails is, but when belenaEtcher asks for a password it usually wants the password on your system (for example, if you're running it on a Mac, you enter your Mac user's password).

**Comment by Ryan5013** [comment]
I tried that but it did not work

**Comment by eiddor** [comment]
Does your account have administrator access?  It's hard to tell without know what kind of system you're running on, but maybe you need to run it as administrator (I think that's a Windows thing).

**Comment by Ryan5013** [comment]
I am using a iMac

**Comment by Ryan5013** [comment]
software version Mac OS Big Sur 11.5.1

**Comment by eiddor** [comment]
On my Mac, I just enter my regular Mac password.

See this thread: https://github.com/balena-io/etcher/issues/2997

**Comment by eiddor** [comment]
Just a note - This repo is for balenaSound.

**Comment by Ryan5013** [comment]
THANKS FOR THE HELP I WILL HAVE TO FIGURE IT OUT IF THERE IS NOTHING ELSE YOU KNOW TO HELP
