### ISSUE TITLE
[spotify] Consider switching to spotifyd

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#518]
Spotifyd is more actively maintained and more popular than librespot/raspotify. There are also docker images available that are extremely less bloated than raspotify.

References:
- https://hub.docker.com/r/ggoussard/spotifyd
- https://github.com/Spotifyd/spotifyd

**Comment by eiddor** [comment]
This could be an issue: 

> Common issues
> Spotifyd will not work without Spotify Premium

**Comment by tmigone** [comment]
So `librespot` is the only true library, `spotifyd` and `raspotify` are packaged solutions that rely on `librespot`. As such we are moving away from `raspotify` as it's an additional layer with it's own versioning scheme that also doesn't support all the architectures we need. 

From now own, we'll use our own prebuilt docker images running `librespot`: https://github.com/tmigone/librespot-docker
