### ISSUE TITLE
Airplay2 implementation now that shairport-sync has it

### ISSUE THREAD

**Issue by nmcc1212** [balenalabs/balena-sound#540]
**Is your feature request related to a problem? Please describe.**
To implement airplay2

**Describe the solution you'd like**
Shairport-sync now has airplay2 support in its development branch (https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md) so could balena-sound also make a new branch using the new airplay2 compatibility found in shairport-sync

**Comment by npmstart-pray** [comment]
Wait for release.  dev is to work issues out unless you're a willing beta tester
