### ISSUE TITLE
RPi Zero W with Adafruit bonnet with no audio

### ISSUE THREAD

**Issue by ssombra** [balenalabs/balena-sound#542]
Just installed balena sound on a RPi Zero W with an Adafruit speaker bonnet following the online instructions. Everything seems ok, the services are running, but I don't get any audio. I checked the troubleshooting page but no luck. I tried both the spotify cllient and the airplay client and none of them works: I can select the "BALENASOUND SPOTIFY" option in the Spotify app, but when hitting play there is not audio. In addition to that, I can see that the progess bar sometimes goes back one second and continues playing. 
any idea what am I doing wrong?

**Comment by TurtleRad** [comment]
Same problem here. Tried it out on RPi3 and RPi4. I can output from my devices to BalenaSound on bluetooth, Airplay and SpotifyConnect; there's just no sound exiting the Pi's.

**Comment by jannis3005** [comment]
Same here, just updated from 03f4b6b to 961b818, and audio stopped working

**Comment by tmigone** [comment]
Should be fixed by https://github.com/balenalabs/balena-sound/pull/547, update to v3.8.4 to get the fix!
