### ISSUE TITLE
RPI3B or RPI4 -> No sound whatsoever

### ISSUE THREAD

**Issue by Mehrdadg** [balenalabs/balena-sound#544]
Hi 
I am new to this BalenaSound but I have been trying for the past many hours to get BalenaSound working on multiple RPIs without any success. 
I have tried all the trick that was able to find googling (forcing audio to HDMI, 3.5mm jack, deleting vc4-fkms-v3d on Rpi3, ...) and none so far fixed my issue.

I use the cloud app to create an image (for both RPI3 and 4) and go through installing without any issues. I can use my ipad and see the newly configured BalenaSound in my Airplay menus and when I select it, it connects without any issues but there is no sound (yes I even tried increasing the sound on IPAD to max as someone had suggested).

not sure what these warning mean but I figure I post them as it may give rise to some clue on the issue:
 airplay  warning: could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i7" on the system bus.
 airplay  warning: could not acquire an MPRIS interface named "org.mpris.MediaPlayer2.ShairportSync.i7" on the system bus.

 audio  Setting audio routing rules...
 audio  Routing 'balena-sound.input' to 'snapcast'.
 audio  Routing 'balena-sound.output' to 'alsa_output.bcm2835-jack.stereo-fallback'.
 audio  W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
 audio  W: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
 audio  W: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

 sound-supervisor  Error connecting to audio block - Retry failed: connect ECONNREFUSED 172.30.6.117:4317
 sound-supervisor  Error connecting to audio block - Retry failed: connect ECONNREFUSED 172.30.6.117:4317
 sound-supervisor  Connected to PulseAudio at 172.30.6.117:4317
 sound-supervisor  Server protocol version: 35
 sound-supervisor  Client protocol version: 33
 sound-supervisor  Playback started, announcing 172.30.6.117 as multi-room master!
 sound-supervisor  Joining the fleet, requesting master info with fleet-sync...

Anyhow, it looks like a pretty good software but for the life of me I can't get it to work as I get no sound either from HDMI port or 3.5mm jack. By the way I tried the following as well:

open a terminal to the ‘spotify’ container and run install_packages alsa-utils. After that completes you can run speaker-test -c2 -t wav to test the output
  ----> Results is that I hear audio from the HDMI port

Any help is greatly appreciated.
thanks

**Comment by achochia** [comment]
Can confirm same warnings on 2 fresh 32Bit BalenaSound installs on Raspberry Pi 3b+, and on a Raspberry Pi ZeroW with a supported DAC. Been having these issues with the newest version and even using the older 2.38.0 rev1 on my 3B+. Attempts with a 64Bit OS had the same issues, and no fixes specified online helped.

**Comment by Mehrdadg** [comment]
Achochia- The error messages I posted earlier are from fresh install on RPI3B+. I don't have RPI ZeroW to try and don't have DAC.
I am just relying on the Headphone Jack from the RPIs and/or HDMI outputs.
one issue that was raised along ago was related to 64b OS on RPI3 which the recommendation was to remove "vc4-fkms-v3d" from the device which did nothing for me

**Comment by achochia** [comment]
Im just adding more devices and variations to the mix. I had used BalenaSound for years now and this is the first time a fresh install gives me this much headache. I had a working version from a build in September, which correspond to tag ca96642. I think ill try to fork that revision and attempt from there.

**Comment by TurtleRad** [comment]
I would suggest merging this with #543 and #542 … Seems the latest update is breaking the audio outputs on RPi.

**Comment by Maximus48p** [comment]
Confirm no sound output 3.5mm jack on Pi3b+ with AUDIO_OUTPUT on RPI_HEADPHONES.
version 2.83.21+rev1 and 12.11.30.

**Comment by Patrick114** [comment]
Having this issue as well, rolling back to 3.6.19 fixed it

**Comment by Mehrdadg** [comment]
Stupid question... I looked everywhere to see how I can downgrade to version 3.6.19 but I don't see this option available to me.
Any hind is greatly appreciated.
thanks

**Comment by tmigone** [comment]
Should be fixed by https://github.com/balenalabs/balena-sound/pull/547, update to v3.8.4 to get the fix!
