### ISSUE TITLE
The audio interfaces instructions page is not available

### ISSUE THREAD

**Issue by tennisparty** [balenalabs/balena-sound#548]
The webpage is unavailable on GitHub and on https://sound.balenalabs.io/docs/audio-interfaces

**Comment by smokeyjoe1234** [comment]
Can confirm I've been having the same issue with all of the guide pages.

**Comment by iubmadiwtu** [comment]
An error occurred loading this page's template. More information is available in the console.

**Comment by smokeyjoe1234** [comment]
Console is throwing this error:

sound.balenalabs.io/:1 Error while trying to use the following icon from the Manifest: https://sound.balenalabs.io/android-icon-144x144.png (Resource size is not correct - typo in the Manifest?)

I was seeing some 404s earlier, too.

**Comment by tmigone** [comment]
Fixed by #552
