### ISSUE TITLE
Airplay2 support / Chromecast support

### ISSUE THREAD

**Issue by wingnut144** [balenalabs/balena-sound#560]
**Is your feature request related to a problem? Please describe.**

I have a system I'm trying to tie this into and it requires either Airplay2 or Chromecast.  I don't see either listed

**Describe the solution you'd like**
If those 2 options would be added, that would be awesome :)

**Describe alternatives you've considered**

**Additional context**

**Comment by tmigone** [comment]
Hey closing this as it's a repeat issue, see:
- https://github.com/balenalabs/balena-sound/issues/102
- https://github.com/balenalabs/balena-sound/issues/419
