### ISSUE TITLE
Add name differentiation for different services

### ISSUE THREAD

**Issue by chrisys** [balenalabs/balena-sound#58]
Airplay and bluetooth services are named identically so in some situations it's impossible to differentiate between the two. Example from macOS:

![Screenshot 2019-11-19 at 10 41 36](https://user-images.githubusercontent.com/521698/69175845-63558d00-0ab9-11ea-91b0-0bd3d187736e.png)

**Comment by AlexProgrammerDE** [comment]
@chrisys this can be easily fixed by defining service variables. 

If you delete the worlwide device variable and set `BLUETOOTH_DEVICE_NAME` for airplay and bluetooth-audio.

This is not a workaround for people which want to have no variable set, but it is a solution.

**Comment by chrisys** [comment]
@AlexProgrammerDE good thinking! That's a good workaround

**Comment by AlexProgrammerDE** [comment]
@chrisys i fixed it in #95 . I requested you to review.

**Comment by AlexProgrammerDE** [comment]
@chrisys you can now close this issue. You already merged my PR.

**Comment by tmigone** [comment]
Thanks again!
