### ISSUE TITLE
Balena Sound Supported Devices Webpage down

### ISSUE THREAD

**Issue by LabeebQa** [balenalabs/balena-sound#586]
**Description**
Balena Sound Supported Devices Webpage has been reported as not found as of 16:38hrs GMT

1. Open 'https://sound.balenalabs.io/docs/docs/device-support#recommended''
2. You can see "Hey, the page you are looking does not exist!"

**Screenshots**
![image](https://user-images.githubusercontent.com/84878211/176731703-1b117b92-7a84-45b0-bc05-04ef090ccba1.png)
![image](https://user-images.githubusercontent.com/84878211/176731889-9a8dd124-b887-4ff7-88f9-5940060270ac.png)

**Device information**
Browser : Google Chrome Version 103.0.5060.66 (Official Build) (64-bit)
                Microsoft Edge Version 103.0.1264.37 (Official build) (64-bit)

**Comment by mWH4** [comment]
> 'https://sound.balenalabs.io/docs/docs/device-support#recommended''

You typed "/docs" twice. Visit [https://sound.balenalabs.io/docs/device-support/#recommended](https://sound.balenalabs.io/docs/device-support/#recommended).
