### ISSUE TITLE
bluetooth-audio: Volume set to CONNECTION_NOTIFY_VOLUME after connecting

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#78]
When connecting via `bluetooth-audio`, it seems the volume set for notifications (75%) is left as default for system output. Seems like [this](https://github.com/balenalabs/balena-sound/blob/master/bluetooth-audio/bluetooth-udev#L18) is not working.

**Comment by AlexProgrammerDE** [comment]
Maybe is $SYSTEM_OUTPUT_VOLUME% trying to use the `SYSTEM_OUTPUT_VOLUME%` var.

**Comment by tmigone** [comment]
It's actually set to whatever `CONNECTION_NOTIFY_VOLUME` is, which not always is 75%.
