### ISSUE TITLE
Not recognised

### ISSUE THREAD

**Issue by rubyxcubes** [balenalabs/balena-sound#89]
I'm using Raspberry Pi 3 B+ with balenaOS for Raspberry Pi 3 (not the 64-bit Beta version). It connects with Bluetooth properly, but it isn't recognised as a valid sound output device on any device I use. When I plug it into my speakers, I get a buzzing sound and nothing else. What do I do?

**Comment by chrisys** [comment]
Hi @rubyxcubes please start a thread on the balena support forums at https://forums.balena.io - ideally include your device logs and device diagnostics output from the dashboard screen. We'll then be able to help out there.
