### ISSUE TITLE
spotify: Authentication fails if pasword has spaces in it

### ISSUE THREAD

**Issue by tmigone** [balenalabs/balena-sound#90]
Confirmed that a password with spaces in it does not work.

**Comment by AlexProgrammerDE** [comment]
Found the issue:

https://github.com/balenalabs/balena-sound/blob/abb17686d50aac16c1caf1b7909bfcf706a5c423/spotify/start.sh#L11-L14

https://github.com/balenalabs/balena-sound/blob/abb17686d50aac16c1caf1b7909bfcf706a5c423/spotify/start.sh#L17

The password is not saved in: "" which is then seen as a separate command line argument.

**Comment by AlexProgrammerDE** [comment]
@tmigone i opened now a PR. I am not able to test it. Could you do it please?

**Comment by AlexProgrammerDE** [comment]
@tmigone my PR #91 got merged. You can now close this issue.

**Comment by tmigone** [comment]
Thanks!

**Comment by Baryczka** [comment]
This PR could caused other issue:
https://github.com/balenalabs/balena-sound/issues/131
